{{- if .Values.useLegacyProvisioner }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
    {{- if .Values.managedDefaultClass }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
allowVolumeExpansion: true
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  encrypted: "true"
  type: gp2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
  name: gp2
allowVolumeExpansion: true
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  encrypted: "true"
  type: gp2
{{- end }}
